import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Navbar from "../components/Navbar"
import Main from "../components/Main"
import Details from "../components/Details"
import styled from 'styled-components'
import React,{useState} from 'react'
const Container = styled.div`
width: 100vw;
padding:1.5rem 2.5rem;
height: 100vw;
background-color:#F6F6F6 ;
`

export default function Home() {
const [apiData, setApiData] = useState(false)

  return (
    <Container>
      <Head>
        <title>Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar apiData={apiData} setApiData={setApiData}/>
      <Details/>
      <Main apiData={apiData} setApiData={setApiData}/>
    </Container>
  )
}
